--SELECT NAME FROM SYS.TABLES WHERE NAME !='sysdiagrams'

DECLARE @TABLE_I TINYINT = 1
DECLARE @TABLE_MAX TINYINT
DECLARE @TABLE_NAME VARCHAR(50) -- = 'Uye'

DECLARE @TABLES TABLE (N INT, NAME VARCHAR(50))
DECLARE @QUERIES TABLE ( QUERY VARCHAR(MAX) )

INSERT INTO @TABLES (N,NAME) 
    SELECT ROW_NUMBER() OVER( ORDER BY NAME) [N], NAME FROM SYS.TABLES WHERE NAME !='sysdiagrams'

SET @TABLE_MAX = (SELECT MAX(N) FROM @TABLES)

WHILE (@TABLE_I <= @TABLE_MAX)
  BEGIN 
    SET @TABLE_NAME = (SELECT NAME FROM @TABLES WHERE N = @TABLE_I)
    --SELECT @TABLE_NAME
    INSERT INTO @QUERIES
        EXEC CreateAllProceduresForTable @TABLE_NAME ,1,1,1,1  -- Delete,Insert,Trigger,Update
    SET @TABLE_I += 1
  END

SELECT * FROM @QUERIES


