CREATE PROCEDURE get_column_names 
@TABLO_AD varchar(MAX)
AS
SELECT
    TABLE_NAME + '.' + COLUMN_NAME[Tablo.Sutun]
    , DATA_TYPE
    , CHARACTER_MAXIMUM_LENGTH = 
        CASE 
            WHEN CHARACTER_MAXIMUM_LENGTH >  99999 THEN 0
            WHEN ISNULL(CHARACTER_MAXIMUM_LENGTH,-1) = -1 THEN -1
            ELSE CHARACTER_MAXIMUM_LENGTH
            --WHEN ISNULL(CHARACTER_MAXIMUM_LENGTH, 0) = 0 THEN 0
        END
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = @TABLO_AD
    ORDER BY TABLE_NAME

